---
# handlers file for promtail role

- name: restart promtail docker compose
  docker_compose:
    project_src: '{{ promtail_path }}'
    state: present
    services:
      - promtail
    restarted: yes
  listen: restart promtail
  when: promtail_deploy_mode == 'docker'

- name: restart promtail service
  service:
    name: promtail
    enabled: yes
    state: restarted
  listen: restart promtail
  when: promtail_deploy_mode == 'binary'

- name: promtail_daemon_reload_systemd
  become: true
  systemd:
    daemon_reload: true
