---
# defaults file for nextcloud

nextcloud_mysql_root_password:
nextcloud_mysql_password:

nextcloud_version: 23
# https://github.com/nextcloud/notify_push/releases/
nextcloud_notify_push_version: v0.4.0
nextcloud_mariadb_version: 10.5

container_path: /container
nextcloud_path: '{{ container_path }}/nextcloud'
nextcloud_domain: 'nextcloud.{{ ansible_fqdn }}'

nextcloud_php_memory_limit: 512M

# nextcloud_admin_user: nextcloud-admin
# nextcloud_admin_password:

nextcloud_data_dir: './nextcloud-data'

# worker processes for nginx and php
nextcloud_worker_processes: 8

# pull docker images (docker-compose pull)
nextcloud_docker_pull: '{{ global_docker_pull | default(False) }}'

# Database Tuning
nextcloud_mysqld_max_connections: 300
nextcloud_mysqld_query_cache_size: 104857600  # 256MiB: 268435456

# custom database tuning added to mysql.conf
nextcloud_mysql_custom_options: ''
