---
- name: webserver_restart
  docker_compose:
    project_src: '{{ webserver_path }}'
    state: present
    restarted: yes

- name: webserver_restart_nginx
  docker_compose:
    project_src: '{{ webserver_path }}'
    services:
      - web
    state: present
    restarted: yes

- name: webserver_restart_php
  docker_compose:
    project_src: '{{ webserver_path }}'
    services:
      - php
    build: True
    state: present
    restarted: yes

- name: webserver_recreate_sftp
  docker_compose:
    project_src: '{{ webserver_path }}'
    services:
      - sftp
    state: present
    recreate: always
    restarted: yes
