#
# Managed by Ansible
#

groups:
  - name: http checks
    rules:
      - alert: EndpointDown
        expr: probe_success == 0
        for: 5m
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for
            more than 5 minutes.'
          summary: Instance {{ $labels.instance }} down
        labels:
          severity: critical

      - alert: http probe 2xx
        expr: "probe_http_status_code{job=~'http_2xx(_redirect)?'} > 299 OR probe_http_status_code{job=~'http_2xx(_redirect)?'} < 200"
        annotations:
          summary: "{{ $labels.instance }} - Not OK"
          description: "Expected HTTP status 2xx, got {{ $value }} for {{ $labels.instance }}"
        labels:
          severity: critical

      - alert: http probe 3xx
        expr: "probe_http_status_code{job='http_3xx'} > 399 OR probe_http_status_code{job='http_3xx'} < 300"
        annotations:
          summary: "{{ $labels.instance }} - Not 3xx"
          description: "Expected HTTP status 3xx, got {{ $value }} for {{ $labels.instance }}"
        labels:
          severity: critical

      - alert: http probe 403
        expr: "probe_success{job='http_403'} == 0"
        annotations:
          summary: "{{ $labels.instance }} - HTTP failure"
        labels:
          severity: critical

      - alert: http probe healthz
        expr: "probe_failed_due_to_regex{job='http_healthz'} == 1"
        for: 5m
        annotations:
          summary: "{{ $labels.instance }} - Healthz check failed"
        labels:
          severity: warning

      - alert: http probe zammad
        annotations:
          summary: '{{ $labels.instance }} - Zammad check failed'
        expr: probe_failed_due_to_regex{job='http_zammad'} == 1
        for: 5m
        labels:
          severity: warning


  - name: ssl_expiry.rules
    rules:
      - alert: SSLCertExpiringSoon
        expr: round((probe_ssl_earliest_cert_expiry - time()) / 86400, 1) < 14
        for: 10m
        annotations:
          description: "certificate on {{ $labels.instance }} will expire in {{ $value }} days"
          summary: "SSL certificate expiration {{ $labels.instance }}"
        labels:
          severity: warning

      - alert: SSLCertExpiringSoon
        expr: round((probe_ssl_earliest_cert_expiry - time()) / 86400, 1) < 7
        for: 10m
        annotations:
          description: "certificate on {{ $labels.instance }} will expire in {{ $value }} days"
          summary: "SSL certificate expiration {{ $labels.instance }}"
        labels:
          severity: critical
