#
# Managed by Ansible
#

groups:
  - name: http checks
    rules:
      - alert: EndpointDown
        expr: probe_success == 0
        for: 5m
        annotations:
          summary: 'Endpoint down: {{ $labels.host }}'
          description: 'Target has been down for more than 5 minutes. Job: {{ $labels.job }} for {{ $labels.instance }}'
        labels:
          severity: critical

      - alert: http probe 2xx
        expr: "probe_http_status_code{job=~'http_2xx(_redirect)?'} > 299 OR probe_http_status_code{job=~'http_2xx(_redirect)?'} < 200"
        for: 1m
        annotations:
          summary: "HTTP Not OK: {{ $labels.host }}"
          description: "Expected HTTP status 2xx, got {{ $value }} for {{ $labels.instance }}"
        labels:
          severity: critical

      - alert: http probe 3xx
        expr: "probe_http_status_code{job='http_3xx'} > 399 OR probe_http_status_code{job='http_3xx'} < 300"
        for: 1m
        annotations:
          summary: "HTTP Not 3xx: {{ $labels.host }}"
          description: "Expected HTTP status 3xx, got {{ $value }} for {{ $labels.instance }}"
        labels:
          severity: critical

      - alert: http probe 403
        expr: "probe_success{job='http_403'} == 0"
        for: 1m
        annotations:
          summary: "HTTP failure - {{ $labels.host }}"
          description: "HTTP failure - {{ $labels.instance }}"
        labels:
          severity: critical

      - alert: http probe healthz
        expr: "probe_failed_due_to_regex{job='http_healthz'} == 1"
        for: 5m
        annotations:
          summary: "Healthz check failed: {{ $labels.host }}"
          description: "Healthz check failed: {{ $labels.instance }}"
        labels:
          severity: warning

      - alert: http probe zammad
        expr: probe_failed_due_to_regex{job='http_zammad'} == 1
        for: 5m
        annotations:
          summary: 'Zammad check failed: {{ $labels.host }}'
          description: 'Zammad health check failed: {{ $labels.instance }}'
        labels:
          severity: warning


  - name: ssl_expiry.rules
    rules:
      - alert: SSLCertExpiringSoon
        expr: round((probe_ssl_earliest_cert_expiry - time()) / 86400, 1) < 14
        for: 10m
        annotations:
          summary: "SSL certificate expiration {{ $labels.host }}"
          description: "certificate on {{ $labels.instance }} will expire in {{ $value }} days"
        labels:
          severity: warning

      - alert: SSLCertExpiringSoon
        expr: round((probe_ssl_earliest_cert_expiry - time()) / 86400, 1) < 7
        for: 10m
        annotations:
          summary: "SSL certificate expiration {{ $labels.host }}"
          description: "certificate on {{ $labels.instance }} will expire in {{ $value }} days"
        labels:
          severity: critical
