---

# use compose to send a SIGHUP to blacbox's process (PID=1)
- name: dependabot reload
  command: 'docker-compose exec -T dependabot kill -HUP 1'
  args:
    chdir: '{{ dependabot_path }}'

# regenerates nginx conf from templates
# this is not the same as just reloading the config
- name: restart nginx config generator of webproxy
  docker_compose:
    project_src: '{{ webproxy_path }}'
    services:
      - 'docker-gen'
      - 'nginx'
    state: present
    restarted: yes
  listen:
    - dependabot_regenerate_webproxy_config

...
