# Sanoid Configuration (automatic snapshotting of zfs datasets)

# - name: install sanoid
#   apt:
#     name: sanoid
#     state: present

- name: Install new version of sanoid
  apt:
    deb: https://ftp.debian.org/debian/pool/main/s/sanoid/sanoid_2.1.0-1.1_all.deb
    state: present

- name: create conf directory
  file:
    path: /etc/sanoid
    state: directory
    owner: root
    group: root
    mode: 0750

- name: deploy sanoid.conf
  copy:
    content: "{{ sanoid_conf }}\n"
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: 0640
