---

- name: vector_daemon_reload_systemd
  become: true
  systemd:
    daemon_reload: true

- name: validate vector config # noqa no-changed-when
  command: /usr/bin/vector validate --config-toml /etc/vector/*.toml
  listen:
    - restart vector
    - reload vector

- name: restart vector
  systemd:
    name: vector
    state: restarted

- name: reload vector
  systemd:
    name: vector
    state: reloaded
