- name: install nvme cli packages
  apt:
    name:
      - nvme-cli
      - pciutils
    state: present

- name: copy nvme_metrics.py script
  copy:
    src: nvme_metrics.py
    dest: /usr/local/bin/nvme_metrics.py
    owner: root
    group: root
    mode: '0750'

- name: cronjob for nvme metrics
  cron:
    name: nvme_metrics
    minute: "*/10"
    hour: "*"
    user: root
    job: '/usr/local/bin/nvme_metrics.py -o prometheus > {{ node_exporter_textfile_dir }}/nvme.prom.$$ && mv {{ node_exporter_textfile_dir }}/nvme.prom.$$ {{ node_exporter_textfile_dir }}/nvme.prom'
    cron_file: nvme_metrics
