---
version: '3'
services:
  minio:
    image: minio/minio:{{ minio_version }}
    volumes:
      - ./data:/data
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: '{{ minio_access_key }}'
      MINIO_SECRET_KEY: '{{ minio_secret_key }}'
      MINIO_BROWSER: 'off'
      VIRTUAL_HOST: '{{ minio_domains | join(",") }}'
      LETSENCRYPT_HOST: '{{ minio_domains | join(",") }}'
      LETSENCRYPT_EMAIL: '{{ letsencrypt_email }}'
    command: server /data
    restart: always
    networks:
      - webproxy
{% if minio_console_enable %}
  console:
    image: minio/console:{{ minio_console_version }}
    expose:
      - 9090
    environment:
      CONSOLE_PBKDF_PASSPHRASE: '{{ minio_console_pbkdf_passphrase }}'
      CONSOLE_PBKDF_SALT: '{{ minio_console_pbkdf_salt }}'
      CONSOLE_MINIO_SERVER: 'https://{{ minio_domain }}'
      MINIO_BROWSER_REDIRECT_URL: 'https://{{ minio_console_domain }}'
      VIRTUAL_HOST: '{{ minio_console_domain }}'
      LETSENCRYPT_HOST: '{{ minio_console_letsencrypt_host }}'
      LETSENCRYPT_EMAIL: '{{ letsencrypt_email }}'
    command: server
    restart: always
    networks:
      - webproxy
{% endif %}

networks:
  webproxy:
    external:
      name: webproxy
