---
container_path: /container
kimai_path: '{{ container_path }}/kimai'
kimai_domain: '{{ ansible_fqdn }}'

kimai_version: '2.0.29' # https://www.kimai.org/documentation/installation.html
kimai_php_version: '8.2'
kimai_mariadb_version: '10.11'

kimai_mysql_database: kimai
kimai_mysql_user: kimai
# kimai_mysql_root_password:
# kimai_mysql_password:

# email configuration https://www.kimai.org/documentation/emails.html
kimai_mailer_from: 'kimai@{{ kimai_domain }}'
kimai_mailer_url: null://null # disabled
# kimai_mailer_url: # 'smtp://username:password@mx.example.com:587?encryption=tls&auth_mode=plain'

# REQUIRED
# kimai_app_secret: change_this_to_something_unique

# override php max_execution_time
kimai_max_execution_time: 60

kimai_php_extensions:
  - gd
  - intl
  - imagick
  - opcache
  - zip
  # - mcrypt
  - pdo_mysql
  - mysqli
  # - xdebug
  - xsl
  - mbstring
