---
# defaults file for zammad
zammad_path: '{{ container_path }}/zammad'
zammad_domain: 'zammad.{{ ansible_fqdn }}'
zammad_letsencrypt_host: '{{ zammad_domain }}'

# Version as on docker hub: https://hub.docker.com/r/zammad/zammad-docker-compose/tags
zammad_version: latest # 5.2.3-38
zammad_memcached_image: memcached:1.6.17-alpine
zammad_elasticsearch_image: bitnami/elasticsearch:8.5.1
zammad_postgres_image: postgres:15.0-alpine
zammad_redis_image: redis:6.2.5-alpine

# to be replaced in host_vars
zammad_postgres_user: zammad
# zammad_postgres_pass:

zammad_backup_hold_days: 10

# pull docker images (docker-compose pull)
zammad_docker_pull: '{{ global_docker_pull | default(False) }}'

# rebuild elasticsearch index on every fresh start
# for big installations it can take more than 1h (27'000 Tickets)
# alternative: reindex manually:
# docker-compose exec zammad-railsserver rake zammad:searchindex:rebuild
zammad_elasticsearch_reindex: True

# expose elasticsearch readonly through webproxy (for Grafana integration)
zammad_elasticsearch_expose: False
# zammad_elasticsearch_htpasswd:
zammad_elasticsearch_domain: 'es.{{ zammad_domain }}'
webproxy_path: /container/webproxy

# Elasticsearch RAM allocation (Java Xms, Xmx). valid format: 512m, 2g
# default: 40% of total memory
zammad_elasticsearch_memory: '{{ (ansible_memtotal_mb * 0.4) | round | int }}m'

# customize knowledge base html template.
zammad_kb_html_custom: False
# zammad_kb_html:
