---
# https://hub.docker.com/r/victoriametrics/vmagent/tags?page=1&ordering=last_updated
victoriametrics_version: latest
victoriametrics_vmagent_version: '{{ victoriametrics_version }}'
victoriametrics_vmalert_version: '{{ victoriametrics_version }}'

victoriametrics_domain: 'metrics.{{ ansible_fqdn }}'

# retention period (months) https://victoriametrics.github.io/#retention
victoriametrics_retention_period: 3
victoriametrics_big_merge_concurrency: 0

container_path: /container
victoriametrics_path: '{{ container_path }}/victoriametrics'
victoriametrics_docker_pull: '{{ global_docker_pull | default(False) }}'

# storage path for metrics data
victoriametrics_storage_path: '{{ victoriametrics_path }}/vmdata'

victoriametrics_htpasswd_read:
victoriametrics_htpasswd_write:
victoriametrics_htpasswd_admin:

victoriametrics_alertmanager_address: alertmanager.example.com
victoriametrics_alertmanager_port: 443
victoriametrics_alertmanager_scheme: https
victoriametrics_alertmanager_url: '{{ victoriametrics_alertmanager_scheme }}://{{ victoriametrics_alertmanager_address }}:{{ victoriametrics_alertmanager_port }}/'
victoriametrics_alertmanager_user: ''
victoriametrics_alertmanager_password: ''

# Alertmanager source can link to graph in grafana.
victoriametrics_grafana_datasource_name: VictoriaMetrics
victoriametrics_vmalert_evaluation_interval: 1m
victoriametrics_vmalert_external_url: 'https://grafana.yourdomain.com'
victoriametrics_vmalert_external_source: explore?orgId=1&left=["now-1h","now","{{ victoriametrics_grafana_datasource_name }}",{"expr":"{% raw %}{{$$expr|quotesEscape|crlfEscape|pathEscape}}{% endraw %}"}]

# external labels added to all alerts. To see and filter in alertmanager where the alert is coming from
victoriametrics_vmalert_external_labels:
  - 'alertsource={{ victoriametrics_domain }}'

victoriametrics_blackbox_image: prom/blackbox-exporter
victoriametrics_blackbox_version: master # if unstable v0.18.0 can be used

# define your targets, creates files in file_sd/<name>.<job>.yml
victoriametrics_file_sd_config: []
  # - job: http_2xx
  #   name: production
  #   config:
  #     - labels:
  #         environment: production
  #       targets:
  #         - https://example.com/

# additional blackbox_exporter modules
victoriametrics_blackbox_modules: {}

victoriametrics_scrape_configs: []
