---
# handlers file for nextcloud


- name: nextcloud_docker-compose-build
  docker_compose:
    project_src: '{{ nextcloud_path }}'
    state: present
    build: yes
    pull: yes
  notify: nextcloud_docker-compose-up

- name: nextcloud_docker-compose-up
  docker_compose:
    project_src: '{{ nextcloud_path }}'
    state: present

- name: nextcloud_docker-compose-restart
  docker_compose:
    project_src: '{{ nextcloud_path }}'
    state: present
    restarted: yes
