---
# defaults file for loki deployment
container_path: /container
loki_path: '{{ container_path }}/loki'

# loki_domain: '{{ ansible_fqdn }}'
loki_domain: "loki.{{ ansible_fqdn }}"
loki_version: 2.3.0

# htpasswd -B -n username
loki_htpasswd: |
  testuser:$2y$05$5RJ/ieXn7XpXM7R97IZKEOfFLWEo3B0W1KGNQKuArAg3Bt7E9o8Qa

loki_htpasswd_push_only: |
  testuser:$2y$05$5RJ/ieXn7XpXM7R97IZKEOfFLWEo3B0W1KGNQKuArAg3Bt7E9o8Qa

loki_docker_pull: '{{ global_docker_pull | default(False) }}'

loki_alertmanager_url: "" # http://alertmanager:9093

loki_push_access_log: False

# authentication by subrequest for push_only
loki_auth: basic # basic/request

# for loki_auth: request
loki_auth_request_uri: # https://validator.example.com/api/logserveraccess
loki_auth_request_cache_time: 15m
loki_auth_request_cache_time_403: 30s


loki_nginx_gateway_conf_template: '{{ "auth_basic-site.conf" if loki_auth == "basic" else "auth_request-site.conf" }}'

loki_rules: []

loki_storage_boltdb_shipper_cache_ttl: 24h  # Can be increased for faster performance over longer query periods, uses more disk space
loki_chunk_store_max_look_back_period: 90d
loki_table_manager_retention_period: 91d # needs to be bigger than look back period

loki_limits_ingestion_rate_mb: 4
loki_limits_ingestion_burst_size_mb: 6
