# use include_role to workaround issue with run_once.
# a task with run_once is run on the first host in a play,
# if the run_once task is skipped because the role has a condition, then, the task will never run.
- name: import cloudalchemy.node_exporter
  include_role:
    name: cloudalchemy.node_exporter
    apply:
      tags:
        - node_exporter
        - node
  when: manage_node_exporter | default(False)
  tags:
    - node_exporter
    - node

# use file_sd to only add target when configured
- name: node_exporter-vmagent integration. create file_sd target for local node exporter.
  copy:
    dest: /opt/vic-vmagent/file_sd_configs/local.node.yml
    content: |
      #
      # Managed by ansible
      #
      - labels:
          instance: '{{ ansible_fqdn }}'
          host: '{{ ansible_hostname }}'
        targets:
          - 127.0.0.9:9100
    owner: vic_vm_agent
    group: vic_vm_agent
    mode: '0640'
  when:
    - manage_node_exporter | default(False)
    - node_exporter_vmagent_integration | default(True)
  tags:
    - node_exporter
    - node
