---

- name: import webserver role with vars for matomo
  import_role:
    name: teamapps.general.webserver
  vars:
    webserver_path: '{{ matomo_path }}'
    webserver_domain: '{{ matomo_domain }}'
    webserver_php_enable: True
    webserver_mysql_enable: True
    webserver_mysql_root_password: '{{ matomo_mysql_root_password }}'
    webserver_mysql_database: '{{ matomo_mysql_database }}'
    webserver_mysql_user: '{{ matomo_mysql_user }}'
    webserver_mysql_password: '{{ matomo_mysql_password }}'
    webserver_document_root: matomo
  tags:
    - matomo

- name: matomo console wrapper
  copy:
    content: |
      #!/bin/bash
      set -eu
      dir="$(dirname $(readlink -f $0))"
      cd $dir
      if [ -t 0 ] ; then
        tty=""
      else
        tty="-T"
      fi
      /usr/local/bin/docker-compose exec ${tty} -u www-data php matomo/console "$@"
    dest: '{{ matomo_path }}/matomo-console.sh'
    owner: root
    group: root
    mode: 0750
  tags:
    - matomo

- name: setup a cronjob for matomo archiving
  cron:
    name: matomo
    minute: "*/10"
    hour: "*"
    user: root
    job: '{{ matomo_path }}/matomo-console.sh core:archive --concurrent-requests-per-website=3 -vvv --url=http://web:8080/ > /var/log/matomo-archive.log'
    cron_file: matomo
  tags:
    - matomo
