# Inner Task file for syncoid

- name: copy public key # noqa:no-handler
  authorized_key:
    user: root
    key: '{{ _syncoid_id_ed25519.public_key }}'
    comment: 'syncoid@{{ ansible_fqdn }} {{ base_authorized_keys_marker }}'
  delegate_to: '{{ syncoid_source_host_ssh }}'
  when:
    - not ansible_check_mode or not _syncoid_id_ed25519.changed # on

- name: "create cronjob for syncoid pull {{ syncoid_dataset }}"
  cron:
    cron_file: syncoid_{{ syncoid_source_host }}
    name: syncoid pull {{ syncoid_source_dataset }} from {{ syncoid_source_host }}
    minute: "{{ syncoid_cron_minute }}"
    hour: "{{ syncoid_cron_hour }}"
    user: root
    job: >
      /usr/sbin/syncoid
      --source-bwlimit={{ syncoid_source_bwlimit }}
      --recursive
      {% if syncoid_dumpsnaps %}--dumpsnaps{% endif %}
      {{ ['--exclude='] | product(syncoid_exclude) | map('join') | list | join(' ') }}
      --sendoptions="Lc e w"
      --sshkey=/root/.ssh/syncoid_id_ed25519
      --sshoption StrictHostKeyChecking=accept-new
      root@{{ syncoid_source_host_ssh }}:{{ syncoid_source_dataset }}
      {{ syncoid_dest_dataset }}
      >> /var/log/syncoid/cron-{{ syncoid_source_host }}-{{ syncoid_source_dataset | replace('/', '_') }}.log 2>&1
