- name: victoriametrics-restart-gateway
  docker_compose:
    project_src: '{{ victoriametrics_path }}'
    state: present
    services:
      - authproxy
    restarted: yes

# validation in the template won't work because %s expansion won't be reachable from within the container
- name: vmalert validate config
  command: docker-compose run --rm -T vmalert -dryRun -rule=/etc/alerts/*.yml
  args:
    chdir: "{{ victoriametrics_path }}" # to run docker-compose in the correct directory

# use compose to send a SIGHUP to vmalert' process (PID=1)
- name: vmalert reload
  command: 'docker-compose exec -T vmalert kill -HUP 1'
  args:
    chdir: '{{ victoriametrics_path }}'

- name: victoriametrics-vmagent-reload
  command: 'docker-compose exec -T vmagent kill -HUP 1'
  args:
    chdir: '{{ victoriametrics_path }}'

- name: victoriametrics-vmagent-restart
  docker_compose:
    project_src: '{{ victoriametrics_path }}'
    state: present
    services:
      - vmagent
    restarted: yes

# use compose to send a SIGHUP to blacbox's process (PID=1)
- name: blackbox reload
  command: 'docker-compose exec -T blackbox kill -HUP 1'
  args:
    chdir: '{{ victoriametrics_path }}'
