---
vmagent_repo_url: "https://github.com/VictoriaMetrics/VictoriaMetrics"
vmagent_download_url: "{{ vmagent_repo_url }}/releases/download/{{ vmagent_version }}/vmutils-amd64-{{ vmagent_version }}.tar.gz"
vmagent_version: "v1.63.0"
vmagent_system_user: "vic_vm_agent"
vmagent_system_group: "{{ vmagent_system_user }}"
vmagent_config_dir: "/opt/vic-vmagent"
vmagent_sd_config_dir: "{{ vmagent_config_dir }}/file_sd_configs"

# Remote write configuration
vmagent_remotewrite_url: "http://localhost:8428/api/v1/write"
vmagent_remotewrite_username: ""
vmagent_remotewrite_password: ""

# Dict representing set of arguments for vmagent
vmagent_service_args:
  httpListenAddr: 127.0.0.9:8429
  promscrape.config: "{{ vmagent_config_dir }}/config.yml"
  remoteWrite.url: "{{ vmagent_remotewrite_url }}"
  remoteWrite.tmpDataPath: /tmp/vmagent
  remoteWrite.basicAuth.username: '{{ vmagent_remotewrite_username }}'
  remoteWrite.basicAuth.password: '{{ vmagent_remotewrite_password }}'

vmagent_scrape_config:
  global:
    scrape_interval: 10s
    external_labels:
      scraper_instance: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"
  scrape_configs:
    - job_name: "vmagent"
      static_configs:
        - targets: [127.0.0.9:8429]
          labels:
            instance: '{{ ansible_fqdn }}'
            host: '{{ ansible_hostname }}'
    - job_name: node
      file_sd_configs:
        - files:
            - "{{ vmagent_sd_config_dir }}/*.node.yml"

# use control or remote host to download installation archive
vmagent_install_download_to_control: true
vmagent_local_download_dir: /tmp

# Sets environment for downloading archive
vmagent_proxy_http: ""
vmagent_proxy_https: ""

vmagent_exec_start_post: ""
vmagent_exec_stop: ""

# define your targets, creates files in <vmagent_sd_config_dir>/<name>.<job>.yml
vmagent_file_sd_config: []
  # - job: node
  #   name: local
  #   config:
  #     - labels:
  #         instance: '{{ ansible_fqdn }}'
  #         host: '{{ ansible_hostname }}'
  #       targets:
  #         - 127.0.0.1:9100
