---

- name: alertmanager-check-config
  # start new alertmanager container, entrypoint amtool
  command: 'docker-compose run -T --entrypoint amtool alertmanager check-config /etc/alertmanager/alertmanager.yml'
  args:
    chdir: '{{ alertmanager_path }}'
  listen:
    - alertmanager reload

# use compose to send a SIGHUP to blacbox's process (PID=1)
- name: alertmanager reload
  command: 'docker-compose exec -T alertmanager kill -HUP 1'
  args:
    chdir: '{{ alertmanager_path }}'

# regenerates nginx conf from templates
# this is not the same as just reloading the config
- name: nginx gen
  command: 'docker-compose restart nginx-gen'
  args:
    chdir: '{{ webproxy_path }}'
...
