---
webproxy_path: /container/webproxy
container_path: /container
webserver_path: '{{ container_path }}/webserver'

webserver_domain: '{{ ansible_fqdn }}'
webserver_addon_domains: []

webserver_domains: '{{ [webserver_domain] + webserver_addon_domains }}'

webserver_document_root: httpdocs
webserver_nginx_template: site.conf
webserver_client_max_body_size: 10M

# pull docker images (docker-compose pull)
webserver_docker_pull: '{{ global_docker_pull | default(False) }}'

webserver_php_enable: False
webserver_php_image: '' # if set, use image from registry, else build image
webserver_php_version: '8'
webserver_php_memory_limit: 4G
webserver_php_apt_packages: []
  # - git
webserver_php_extensions:
  - gd
  - intl
  - imagick
  - opcache
  - zip
  - mcrypt
  - pdo_mysql
  - mysqli
  - xdebug
  - soap
  - apcu
webserver_sftp_enable: False
webserver_sftp_port: 2222
webserver_sftp_authorized_keys: ''

webserver_mysql_enable: False
webserver_mariadb_version: latest
# webserver_mysql_root_password:
# webserver_mysql_database:
# webserver_mysql_user:
# webserver_mysql_password:

webserver_basic_auth: ''

# PhpMyAdmin interface on /.myadmin
webserver_myadmin_enable: False
# htpasswd file content (if webserver_basic_auth is used, it should also contain the myadmin_htpasswd credentials)
webserver_myadmin_htpasswd: ''
webserver_myadmin_absolute_uri: https://{{ webserver_domain }}/.myadmin/
