- name: verify that the minio secrets are set
  assert:
    that:
      - "{{ assert_var }} is defined"
      - "{{ assert_var }} | length > 0"
      - "{{ assert_var }} != None"
    fail_msg: "{{ assert_var }} needs to be set!"
  loop_control:
    loop_var: assert_var
  with_items:
    - minio_access_key
    - minio_secret_key

- name: verify that the minio console secrets are set
  when: minio_console_enable
  assert:
    that:
      - "{{ assert_var }} is defined"
      - "{{ assert_var }} | length > 0"
      - "{{ assert_var }} != None"
    fail_msg: "{{ assert_var }} needs to be set!"
  loop_control:
    loop_var: assert_var
  with_items:
    - minio_console_pbkdf_passphrase
    - minio_console_pbkdf_salt

- name: minio_directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - '{{ minio_path }}'

- name: deploy config
  template:
    src: '{{ item }}'
    dest: '{{ minio_path }}/{{ item }}'
    owner: root
    group: root
    mode: '0640'
  with_items:
    - docker-compose.yml
  notify: minio_restart

- name: minio_docker-compose-up
  docker_compose:
    project_src: '{{ minio_path }}'
    state: present
    pull: '{{ minio_docker_pull }}'
    remove_orphans: yes
