- name: assert webserver_php_version is a string (otherwise 10.10 = 10.1)
  assert:
    that: webserver_php_version is string
    # that: (item | type_debug == "string" )
  tags: type_assert

- name: php config directory ({{ webserver_domain }})
  file:
    path: '{{ webserver_path }}/php'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: deploy php config ({{ webserver_domain }})
  template:
    src: '{{ item }}'
    dest: '{{ webserver_path }}/{{ item }}'
    owner: root
    group: root
    mode: '0640'
  with_items:
    - php/Dockerfile
    - php/fpm-custom.ini
    - php/php-override.ini
  notify: webserver_restart_php

- name: remove old php files ({{ webserver_domain }})
  file:
    path: '{{ webserver_path }}/{{ item }}'
    state: absent
  with_items:
    - log.conf
    - php/zz-custom.ini
    - php/fpm-log.ini
