- name: create sftp directory ({{ webserver_domain }})
  file:
    path: '{{ webserver_path }}/sftp/'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: sftp generate host keys ({{ webserver_domain }})
  command: ssh-keygen -t {{ item }} -f {{ webserver_path }}/sftp/ssh_host_{{ item }}_key -P ""
  args:
    creates: "{{ webserver_path }}/sftp/ssh_host_{{ item }}_key"
  with_items:
    - rsa
    - ed25519
  notify: webserver_recreate_sftp

- name: sftp authorized_keys ({{ webserver_domain }})
  copy:
    content: '{{ webserver_sftp_authorized_keys }}'
    dest: "{{ webserver_path }}/sftp/authorized_keys"
    owner: www-data
    group: www-data
    mode: '0640'
  notify: webserver_recreate_sftp
