---
# defaults file for nexus
nexus_path: '{{ container_path }}/nexus'
nexus_domain: 'nexus.{{ ansible_fqdn }}'

# docker image tag https://hub.docker.com/r/sonatype/nexus3/tags
nexus_version: latest

# pull docker images (docker-compose pull)
nexus_docker_pull: '{{ global_docker_pull | default(False) }}'
